name: Build and Deploy to GitHub Pages

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install root dependencies
      run: npm ci
      
    - name: Install client dependencies
      run: |
        cd client
        npm ci
        
    - name: Create production environment file
      run: |
        cd client
        echo 'VITE_GITHUB_PAGES=true' > .env.production
        echo 'VITE_API_BASE_URL=' >> .env.production
        
    - name: Build client application
      run: |
        cd client
        npx vite build --mode production --base='./'
      env:
        NODE_ENV: production
        
    - name: Prepare GitHub Pages deployment
      run: |
        mkdir -p dist/public
        if [ -d "client/dist" ]; then
          cp -r client/dist/* dist/public/
        else
          echo "Client build failed - no dist directory found"
          exit 1
        fi
        
    - name: Create static index for GitHub Pages
      run: |
        cd dist/public
        if [ ! -f "index.html" ] || [ "$(wc -l < index.html)" -lt 10 ]; then
          echo "Creating fallback static index.html"
          cp ../../client/index-static.html index.html
        fi
        
    - name: Verify build output
      run: |
        ls -la dist/public/
        echo "Build completed successfully"
        
    - name: Setup GitHub Pages
      uses: actions/configure-pages@v4
      
    - name: Upload build artifacts
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./dist/public
        
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4