name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install Dependencies
        run: npm ci
      
      - name: Setup Environment
        run: |
          # Set up custom domain from repository secret or environment variable
          if [[ ! -z "$CUSTOM_DOMAIN" ]]; then
            echo "Using custom domain: $CUSTOM_DOMAIN"
          fi
          
          # Run our deploy-test script to generate the configuration
          # This ensures all domain and path detection logic matches what we use in deployment
          node deploy-test.js
          
          # Show the generated configuration
          echo "Generated environment configuration:"
          cat .env.github-pages
      
      - name: Export Static Data
        run: node export-static-data.js
      
      - name: Build
        run: |
          # Read environment settings from our config file
          export $(grep -v '^#' .env.github-pages | xargs)
          echo "Building with BASE_PATH=$VITE_BASE_PATH and CUSTOM_DOMAIN=${CUSTOM_DOMAIN:-none}"
          
          # Run the build with these settings
          npm run build
      
      - name: Setup Deployment Directory
        run: |
          mkdir -p deploy
          cp -r dist/public/* deploy/
          touch deploy/.nojekyll
          
          # Create CNAME file if custom domain is specified
          if [[ ! -z "$CUSTOM_DOMAIN" ]]; then
            echo "$CUSTOM_DOMAIN" > deploy/CNAME
            echo "Created CNAME file for $CUSTOM_DOMAIN"
          fi
      
      - name: Fix HTML Files for Custom Domain
        if: env.CUSTOM_DOMAIN != ''
        run: |
          echo "Fixing HTML files for custom domain deployment..."
          
          # Fix index.html - very aggressive path correction
          sed -i 's/<base href="[^"]*"/<base href="\/"/g' deploy/index.html
          
          # Replace all references to repository path with root path
          REPO_NAME=$(echo "$GITHUB_REPOSITORY" | cut -d '/' -f 2)
          sed -i "s/\/$REPO_NAME\//\//g" deploy/index.html
          
          # Ensure asset paths have leading slash
          sed -i 's/href="assets\//href="\/assets\//g' deploy/index.html
          sed -i 's/src="assets\//src="\/assets\//g' deploy/index.html
          
          # Fix CSS url() references
          sed -i "s/url(\/$REPO_NAME\//url(\//g" deploy/index.html
          
          # Add custom domain meta tag
          sed -i 's/<\/head>/<meta name="custom-domain" content="true">\n  <\/head>/g' deploy/index.html
          
          echo "Completed HTML fixes for custom domain"
      
      - name: Create 404.html for SPA Routing
        run: |
          cat > deploy/404.html << 'EOL'
          <!DOCTYPE html>
          <html>
            <head>
              <meta charset="utf-8">
              <title>Redirecting...</title>
              <script>
                // Single Page App redirection
                sessionStorage.setItem('redirect', window.location.pathname);
                window.location.href = '/';
              </script>
            </head>
            <body>
              <h1>Redirecting...</h1>
              <p>If you are not redirected automatically, <a href="/">click here</a>.</p>
            </body>
          </html>
          EOL
      
      - name: Deploy to GitHub Pages
        # Use direct git commands for more reliability
        run: |
          echo "Deploying to GitHub Pages branch..."
          cd deploy
          
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          git init
          git add -A
          git commit -m "Deploy to GitHub Pages"
          
          # Force push to the gh-pages branch
          git push -f https://x-access-token:${{ github.token }}@github.com/${{ github.repository }} HEAD:gh-pages
          
          echo "✅ Successfully deployed to GitHub Pages"