name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Set your default branch here if it's not 'main'

permissions:
  contents: write  # This is crucial - gives permission to write to the repository

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
      
      - name: Build
        run: npm run build
        
      - name: Fix for GitHub Pages SPA routing
        run: |
          # Get repository name from GitHub context
          REPO_NAME=$(echo "$GITHUB_REPOSITORY" | cut -d'/' -f2)
          echo "Using repository name: $REPO_NAME"
          
          # Backup original index.html
          cp dist/public/index.html dist/public/original-index.html
          
          # Create .nojekyll file
          touch dist/public/.nojekyll
          
          # Create 404.html for SPA routing
          cat > dist/public/404.html << EOL
          <!DOCTYPE html>
          <html>
          <head>
            <meta charset="utf-8">
            <title>Redirecting...</title>
            <script>
              // Store the path we're trying to access
              sessionStorage.redirect = location.href;
              // Redirect to the index page
              location.replace("/${REPO_NAME}/");
            </script>
          </head>
          <body>
            <h1>Redirecting...</h1>
          </body>
          </html>
          EOL
          
          # Modify the original index.html to handle redirects
          sed -i "s/<head>/<head>\n  <base href=\"\/${REPO_NAME}\/\">\n  <script>\n    \/\/ Handle redirects from 404.html\n    (function() {\n      var redirect = sessionStorage.redirect;\n      delete sessionStorage.redirect;\n      if (redirect && redirect !== location.href) {\n        history.replaceState(null, null, redirect.replace(location.origin, ''));\n      }\n    })();\n  <\/script>/" dist/public/index.html
          
          echo "GitHub Pages SPA routing fix applied"
      
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # The branch the action should deploy to
          folder: dist/public  # The folder the action should deploy
          clean: true  # Automatically remove deleted files from deploy branch